Image Model Updated (Issue Fixed #15 )
thybag/RPGCampaignManager pull request #26
Opened 2020-10-12 19:17 UTC by JunaidJaved8461

"Size"attribute successfully added. Also size storing the Image table via Image Model
![sizeAttributeadded](https://user-images.githubusercontent.com/72268940/95782378-3ae60b00-0ce9-11eb-828c-1dcffc6d989f.PNG)

2020-10-12 20:04 UTC, thybag requested changes
Hi @JunaidJaved8461 Cheers for contributing!

Had an initial read through, and think there may be an easier way to grab the size info. It'd also be good to include the paid migration within this PR - so it can be merged as a functional unit etc.

Hope my feedback all makes sense.
Bag

2020-10-12 20:04 UTC, thybag commented on app/Models/Campaign/Image.php
> +            $file_name = $img->getClientOriginalName();
Hi @junaidJaved8461 Cheers for contributing!

In this case i believe the  `$img` should be an instance of `Illuminate\Http\UploadedFile`  so you shouldn't need to grab/move the file at all here. In theory type & size should be grabbable via the `->getMimeType()` and `getSize()`.

In terms of storage, it'd be best to store without the `kb` if possible also, that way we can easily aggregate the size of all the uploaded files on a campaign for example, by calling sum on the sizes. (The kb part can then be added in the UI, or accessor if we always want it).

2020-10-12 20:05 UTC, thybag commented on app/Models/Campaign/Image.php
> +            $file_path =  $img -> move(public_path().'/upload/images', $file_name);
the spaces here will likely throw an error

2020-10-13 05:51 UTC, JunaidJaved8461 commented
![without kb](https://user-images.githubusercontent.com/72268940/95820628-d4d9a200-0d41-11eb-926e-c8e3d7362b3a.PNG)
Hi @thybag  Please review the latest commits & gave me feedback & let me know if any changes require!! Thanks

2020-10-13 06:07 UTC, JunaidJaved8461 reviewed
Requested Changes Done!! Let me Know when you review my commits

2020-10-14 07:32 UTC, JunaidJaved8461 commented
@thybag Have you checked my PR after latest commits?

2020-10-15 16:24 UTC, thybag commented on app/Models/Campaign/Image.php
> +            $file_name = $img->getClientOriginalName();
```suggestion
```
This appears unused

2020-10-15 16:40 UTC, JunaidJaved8461 commented
@thybag All Okay then merge it otherwise let me know if any more change required!! Thanks

2020-10-17 13:15 UTC, merged